# Generated by Django 4.0.4 on 2022-06-02 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_pet',
            fields=[
                ('id_category', models.IntegerField(primary_key=True, serialize=False, verbose_name='id categoria pet')),
                ('name_category', models.CharField(max_length=200, verbose_name='nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('idpet', models.IntegerField(primary_key=True, serialize=False, verbose_name='identificador de la mascota')),
                ('namepet', models.CharField(max_length=200, verbose_name='nombre de  la mascota')),
                ('agepet', models.IntegerField(max_length=2, verbose_name='edad de la mascota')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category_pet')),
            ],
        ),
    ]
